In [2]:
set1:set = {1,1,3,3,5,8,7,9,10}
set1.add(11)
set1.add(15)
set1

{1, 3, 5, 7, 8, 9, 10, 11, 15}

In [3]:
for value in set1:
    print(value)

1
3
5
7
8
9
10
11
15


In [10]:
import numpy as np

array1:np.ndarray = np.array(range(1,11))

#陣列運算
array1+10*50

array([501, 502, 503, 504, 505, 506, 507, 508, 509, 510])

In [12]:
display(np.arange(1.3,3.5,0.1))
display(np.linspace(1,2,20))

array([1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4])

array([1.        , 1.05263158, 1.10526316, 1.15789474, 1.21052632,
       1.26315789, 1.31578947, 1.36842105, 1.42105263, 1.47368421,
       1.52631579, 1.57894737, 1.63157895, 1.68421053, 1.73684211,
       1.78947368, 1.84210526, 1.89473684, 1.94736842, 2.        ])

In [39]:
display(np.random.random())
display(np.random.randn(10,5,3))
display(np.random.randint(1,10,size=(10,5)))

0.31332450223248975

array([[[ 1.16115009e+00, -1.59904226e+00,  2.21954188e+00],
        [-1.80677597e+00, -4.81090396e-01, -2.13374980e+00],
        [-1.05473313e+00,  3.66640228e-01,  8.57320626e-01],
        [-1.23192044e-01,  3.66660436e-01, -1.64707869e+00],
        [ 1.03415046e+00, -4.19594080e-01,  1.14173589e+00]],

       [[ 9.28896108e-01,  6.86656367e-01,  9.95575041e-02],
        [-1.27486859e+00,  7.64742728e-01,  6.12329550e-01],
        [-4.05792071e-01, -4.02241194e-01,  2.53453104e+00],
        [-1.18515266e+00,  2.80598351e-01, -1.01273449e+00],
        [-3.29393930e-01,  1.28248861e+00, -1.46703573e+00]],

       [[-6.65421826e-01, -9.07408317e-01, -5.98021082e-01],
        [ 1.86359777e+00, -1.78737987e+00, -8.32910222e-01],
        [ 4.54716239e-01, -3.53420397e-03,  2.21459712e-01],
        [-2.16633982e+00, -6.51102190e-01,  1.31883845e+00],
        [-2.33888588e-01, -3.77922811e-01, -4.09236346e-01]],

       [[-8.51505996e-01,  3.71285064e-01, -3.83737831e-01],
        [-4.264634

array([[6, 3, 9, 4, 2],
       [9, 4, 3, 6, 6],
       [9, 1, 5, 2, 6],
       [1, 5, 4, 1, 8],
       [5, 3, 4, 1, 1],
       [6, 5, 8, 2, 2],
       [4, 8, 5, 7, 9],
       [9, 5, 1, 7, 1],
       [5, 2, 1, 8, 8],
       [3, 2, 1, 9, 9]])